//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralClass.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneralClass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 I20 的當地語系化字串。
        /// </summary>
        internal static string ChargedCopaymentID {
            get {
                return ResourceManager.GetString("ChargedCopaymentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的當地語系化字串。
        /// </summary>
        internal static string ChronicAdjustCaseID {
            get {
                return ResourceManager.GetString("ChronicAdjustCaseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的當地語系化字串。
        /// </summary>
        internal static string DeclareCategoryRepay {
            get {
                return ResourceManager.GetString("DeclareCategoryRepay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的當地語系化字串。
        /// </summary>
        internal static string DeclareCategorySendCheck {
            get {
                return ResourceManager.GetString("DeclareCategorySendCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 30 的當地語系化字串。
        /// </summary>
        internal static string DeclareFilePharmacyDataFormat {
            get {
                return ResourceManager.GetString("DeclareFilePharmacyDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3 的當地語系化字串。
        /// </summary>
        internal static string DeclareMethodWeb {
            get {
                return ResourceManager.GetString("DeclareMethodWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的當地語系化字串。
        /// </summary>
        internal static string DeclareMethodZip {
            get {
                return ResourceManager.GetString("DeclareMethodZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3 的當地語系化字串。
        /// </summary>
        internal static string DispenseByDayAdjustCaseID {
            get {
                return ResourceManager.GetString("DispenseByDayAdjustCaseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 D 的當地語系化字串。
        /// </summary>
        internal static string MedicalHomeCareAdjustCaseID {
            get {
                return ResourceManager.GetString("MedicalHomeCareAdjustCaseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 I21 的當地語系化字串。
        /// </summary>
        internal static string NoChargedCopaymentID {
            get {
                return ResourceManager.GetString("NoChargedCopaymentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的當地語系化字串。
        /// </summary>
        internal static string NormalAdjustCaseID {
            get {
                return ResourceManager.GetString("NormalAdjustCaseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的當地語系化字串。
        /// </summary>
        internal static string OwnExpenseAdjustCaseID {
            get {
                return ResourceManager.GetString("OwnExpenseAdjustCaseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 5 的當地語系化字串。
        /// </summary>
        internal static string QuickSmokeAdjustCaseID {
            get {
                return ResourceManager.GetString("QuickSmokeAdjustCaseID", resourceCulture);
            }
        }
    }
}
